#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: hahaya
disqus_show_comment_count: true

# site
title: 赛特's blog
url: http://seagullyoyo.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: 赛特
author_email: 350021536@qq.com
author_info: <a href="http://seagullyoyo.github.com">seagullyoyo</a>
